remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Neophron Residence Athens
logo: /assets/img/logo.png
description: "Modern hideaway in central Athens."
show_downloads: false
google_analytics:
include: ["assets"]

url: "https://hyper-thanatos.github.io"
baseurl: "/neophron-residence-athens"
